---
  persistentStorage: 
    enabled: true
    storageClassName: "gp2"
    cassandra: 
      storage: "64Gi"
    grafana: 
      storage: "20Gi"
    consul: 
      storage: "8Gi"
    alertManager: 
      storage: "2Gi"
    ingester: 
      storage: "2Gi"
    mysqlVolumeSize: "100Gi"
    etcdVolumeSize: "64Gi"
    mongodbVolumeSize: "64Gi"
    mongoCacheSize: "4"
    keycloakThemeVolumeSize: "5Gi"
    keycloakBackendVolumeSize: "10Gi"
  storkRequired: false
  nodeAffinityLabel: ""
  podAntiAffinity: false
  pxcentralDBPassword: "Password1"
  caCertsSecretName: ""
  oidc: 
    centralOIDC: 
      enabled: true
      defaultUsername: "admin"
      defaultPassword: "admin"
      defaultEmail: "admin@portworx.com"
      keyCloakBackendUserName: "keycloak"
      keyCloakBackendPassword: "keycloak"
      clientId: "pxcentral"
      updateAdminProfile: true
    externalOIDC: 
      enabled: false
      clientID: ""
      clientSecret: ""
      endpoint: ""
  postInstallJob: 
    sslEnabled: true
  pxbackup: 
    enabled: true
    orgName: "default"
    callHome: true
    mongoMigration: "complete"
    livenessProbeInitialDelay: 1800
  pxlicenseserver: 
    enabled: false
    internal: 
      enabled: true
      lsTypeUAT: false
      lsTypeAirgapped: false
    external: 
      enabled: false
    mainNodeIP: ""
    backupNodeIP: ""
    adminUserName: "admin"
    adminUserPassword: "Adm1n!Ur"
  pxmonitor: 
    enabled: false
    pxCentralEndpoint: ""
    sslEnabled: false
    oidcClientID: "pxcentral"
    consulBindInterface: ""
    cortex: 
      alertmanager: 
        advertiseAddress: ""
  service: 
    pxCentralUIServiceType: "LoadBalancer"
    pxBackupUIServiceType: "LoadBalancer"
    grafanaServiceType: "NodePort"
    cortexNginxServiceType: "NodePort"
  cassandra: 
    jvm: 
      maxHeapSize: ""
      newHeapSize: ""
  installCRDs: false
  clusterDomain: "cluster.local"
  cassandraUsername: "cassandra"
  cassandraPassword: "cassandra"
  operatorToChartUpgrade: false
  securityContext: 
    runAsUser: 1000
    fsGroup: 1000
    runAsNonRoot: true
  images: 
    pullSecrets: 
      - "docregistry-secret"
    pullPolicy: "Always"
    pxcentralApiServerImage: 
      registry: "docker.io"
      repo: "portworx"
      imageName: "pxcentral-onprem-api"
      tag: "2.3.1"
    pxcentralFrontendImage: 
      registry: "docker.io"
      repo: "portworx"
      imageName: "pxcentral-onprem-ui-frontend"
      tag: "2.3.1"
    pxcentralBackendImage: 
      registry: "docker.io"
      repo: "portworx"
      imageName: "pxcentral-onprem-ui-backend"
      tag: "2.3.1"
    pxcentralMiddlewareImage: 
      registry: "docker.io"
      repo: "portworx"
      imageName: "pxcentral-onprem-ui-lhbackend"
      tag: "2.3.1"
    postInstallSetupImage: 
      registry: "docker.io"
      repo: "portworx"
      imageName: "pxcentral-onprem-post-setup"
      tag: "2.3.1"
    keycloakBackendImage: 
      registry: "docker.io"
      repo: "portworx"
      imageName: "postgresql"
      tag: "11.16.0-debian-11-r5"
    keycloakFrontendImage: 
      registry: "docker.io"
      repo: "portworx"
      imageName: "keycloak"
      tag: "16.1.1"
    keycloakLoginThemeImage: 
      registry: "docker.io"
      repo: "portworx"
      imageName: "keycloak-login-theme"
      tag: "2.2.0"
    keycloakInitContainerImage: 
      registry: "docker.io"
      repo: "portworx"
      imageName: "busybox"
      tag: "1.31"
    mysqlImage: 
      registry: "docker.io"
      repo: "portworx"
      imageName: "mysql"
      tag: "5.7.38"
    ## Images required for enabling px-backup 
    pxBackupImage: 
      registry: "docker.io"
      repo: "portworx"
      imageName: "px-backup"
      tag: "2.3.1"
    mongodbImage: 
      registry: "docker.io"
      repo: "portworx"
      imageName: "mongodb"
      tag: "5.0.10-debian-11-r3"
    ## Images required for enabling px-license-server 
    licenseServerImage: 
      registry: "docker.io"
      repo: "portworx"
      imageName: "px-els"
      tag: "2.0.1"
    ## Images required for enabling px-monitor 
    cortexImage: 
      registry: "docker.io"
      repo: "portworx"
      imageName: "cortex"
      tag: "v1.11.1"
    cassandraImage: 
      registry: "docker.io"
      repo: "portworx"
      imageName: "cassandra"
      tag: "4.0.4-debian-11-r14"
    proxyConfigImage: 
      registry: "docker.io"
      repo: "portworx"
      imageName: "nginx"
      tag: "1.22.0-alpine-v2"
    consulImage: 
      registry: "docker.io"
      repo: "portworx"
      imageName: "consul"
      tag: "1.12.2-debian-11-r14"
    dnsmasqImage: 
      registry: "docker.io"
      repo: "portworx"
      imageName: "go-dnsmasq"
      tag: "release-1.0.7-v2"
    grafanaImage: 
      registry: "docker.io"
      repo: "portworx"
      imageName: "grafana"
      tag: "7.5.16"
    prometheusImage: 
      registry: "docker.io"
      repo: "portworx"
      imageName: "prometheus"
      tag: "v2.35.0"
    prometheusConfigReloadrImage: 
      registry: "docker.io"
      repo: "portworx"
      imageName: "prometheus-config-reloader"
      tag: "v0.56.3"
    prometheusOperatorImage: 
      registry: "docker.io"
      repo: "portworx"
      imageName: "prometheus-operator"
      tag: "v0.56.3"
    memcachedMetricsImage: 
      registry: "docker.io"
      repo: "portworx"
      imageName: "memcached-exporter"
      tag: "v0.9.0"
    memcachedIndexImage: 
      registry: "docker.io"
      repo: "portworx"
      imageName: "memcached"
      tag: "1.6.15-alpine"
    memcachedImage: 
      registry: "docker.io"
      repo: "portworx"
      imageName: "memcached"
      tag: "1.6.15-alpine"
