apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portworx-cassandra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/panchnayak/portworx-poc.git
    targetRevision: HEAD
    path: cassandra
  destination:
    server: https://kubernetes.default.svc
    namespace: cassandra
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true