apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: pnayak-east1
  region: us-east-1
  version: "1.23"
managedNodeGroups:
  - name: storage-nodes
    instanceType: t3.large
    minSize: 3
    maxSize: 3
    volumeSize: 20
    #ami: auto
    amiFamily: AmazonLinux2
    labels: {role: worker, "portworx.io/node-type": "storage"}
    tags:
      nodegroup-role: worker
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
        - arn:aws:iam::803113055342:policy/rancher-portworx-policy
        - arn:aws:iam::803113055342:policy/pn-portworx
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        ebs: true
        fsx: true
        efs: true
        albIngress: true
        cloudWatch: true

availabilityZones: [ 'us-east-1a', 'us-east-1b', 'us-east-1c' ]

