kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: px-sharedv4-sc
provisioner: kubernetes.io/portworx-volume
parameters:
   repl: "2"
   sharedv4: "true"
   sharedv4_svc_type: "ClusterIP"
